apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app1
  source:
    path   : "HelmCharts/MyChart1"
    repoURL: "git@github.com:barambuxxa/argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: gumidu/app1:v1

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
